"""add_owner_id_to_tables_and_relationships

Revision ID: c08568358f6b
Revises: 001
Create Date: 2025-05-29 19:01:45.940225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08568358f6b'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_tables_owner_id_users', 'tables', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_tables_owner_id'), 'tables', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_owner_id'), table_name='tables')
    op.drop_constraint('fk_tables_owner_id_users', 'tables', type_='foreignkey')
    op.drop_column('tables', 'owner_id')
    # ### end Alembic commands ###
